[phases.setup]
nixPkgs = { nodejs = "20", npm = "10" }

[phases.build]
cmds = ["cd backend && npm install", "cd backend && npm run prisma:generate", "cd backend && npm run build"]

[start]
cmd = "cd backend && npm start"
